"""
HackerOne Report Generator

Generates vulnerability reports in HackerOne submission format:
- Summary
- Vulnerability Type (CWE)
- Severity (CVSS if possible)
- Steps to Reproduce
- Impact Statement
- PoC (request/response)
- Remediation Suggestion
"""
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

# Map PHANTOM vuln types to CWE IDs (HackerOne uses CWE classification)
VULN_TYPE_TO_CWE = {
    "sqli": {"cwe": "CWE-89", "name": "SQL Injection"},
    "sqli_blind": {"cwe": "CWE-89", "name": "Blind SQL Injection"},
    "xss_reflected": {"cwe": "CWE-79", "name": "Reflected Cross-Site Scripting (XSS)"},
    "xss_stored": {"cwe": "CWE-79", "name": "Stored Cross-Site Scripting (XSS)"},
    "xss_dom": {"cwe": "CWE-79", "name": "DOM-Based Cross-Site Scripting (XSS)"},
    "cmd_injection": {"cwe": "CWE-78", "name": "OS Command Injection"},
    "rce": {"cwe": "CWE-94", "name": "Remote Code Execution"},
    "ssrf": {"cwe": "CWE-918", "name": "Server-Side Request Forgery (SSRF)"},
    "xxe": {"cwe": "CWE-611", "name": "XML External Entity (XXE)"},
    "idor": {"cwe": "CWE-639", "name": "Insecure Direct Object Reference (IDOR)"},
    "csrf": {"cwe": "CWE-352", "name": "Cross-Site Request Forgery (CSRF)"},
    "lfi": {"cwe": "CWE-98", "name": "Local File Inclusion"},
    "rfi": {"cwe": "CWE-98", "name": "Remote File Inclusion"},
    "open_redirect": {"cwe": "CWE-601", "name": "Open Redirect"},
    "auth_bypass": {"cwe": "CWE-287", "name": "Authentication Bypass"},
    "info_disclosure": {"cwe": "CWE-200", "name": "Information Disclosure"},
    "deserialization": {"cwe": "CWE-502", "name": "Insecure Deserialization"},
    "race_condition": {"cwe": "CWE-362", "name": "Race Condition"},
    "file_upload": {"cwe": "CWE-434", "name": "Unrestricted File Upload"},
    "cors_misconfiguration": {"cwe": "CWE-942", "name": "CORS Misconfiguration"},
    "jwt_vulnerability": {"cwe": "CWE-345", "name": "JWT Token Vulnerability"},
    "prototype_pollution": {"cwe": "CWE-1321", "name": "Prototype Pollution"},
    "cache_poisoning": {"cwe": "CWE-444", "name": "Web Cache Poisoning"},
    "subdomain_takeover": {"cwe": "CWE-284", "name": "Subdomain Takeover"},
}

# Severity to CVSS approximate mapping
SEVERITY_CVSS = {
    "critical": {"score": "9.0-10.0", "rating": "Critical"},
    "high": {"score": "7.0-8.9", "rating": "High"},
    "medium": {"score": "4.0-6.9", "rating": "Medium"},
    "low": {"score": "0.1-3.9", "rating": "Low"},
    "info": {"score": "0.0", "rating": "None"},
}


class HackerOneReport:
    """Generates HackerOne-compatible vulnerability reports."""

    def generate(self, vuln: dict) -> dict:
        """Generate a HackerOne report from a vulnerability dict.

        vuln should have: vuln_type, title, url, method, parameter,
        payload_used, request_data, response_data, severity, remediation, description
        """
        vuln_type = vuln.get("vuln_type", "")
        if hasattr(vuln_type, "value"):
            vuln_type = vuln_type.value

        severity = vuln.get("severity", "medium")
        if hasattr(severity, "value"):
            severity = severity.value

        cwe_info = VULN_TYPE_TO_CWE.get(vuln_type, {"cwe": "CWE-0", "name": vuln_type})
        cvss_info = SEVERITY_CVSS.get(severity, SEVERITY_CVSS["medium"])

        title = vuln.get("title", f"{cwe_info['name']} on {vuln.get('url', 'target')}")
        url = vuln.get("url", "")
        method = vuln.get("method", "GET")
        parameter = vuln.get("parameter", "")
        payload = vuln.get("payload_used", "")
        request_data = vuln.get("request_data", {})
        response_data = vuln.get("response_data", {})

        # Build the markdown report
        summary = self._build_summary(title, cwe_info, url, vuln)
        steps = self._build_steps_to_reproduce(url, method, parameter, payload, request_data)
        impact = self._build_impact(vuln_type, cwe_info, severity, vuln)
        poc = self._build_poc(request_data, response_data, payload)
        remediation = self._build_remediation(vuln.get("remediation", ""), vuln_type)

        markdown = f"""## Summary

{summary}

## Vulnerability Type

- **Type**: {cwe_info['name']}
- **CWE**: {cwe_info['cwe']}
- **CVSS Severity**: {cvss_info['rating']} ({cvss_info['score']})

## Steps to Reproduce

{steps}

## Impact

{impact}

## Proof of Concept

{poc}

## Suggested Remediation

{remediation}

---
*Report generated by PHANTOM Security Scanner — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*
"""

        return {
            "title": title,
            "vuln_type_cwe": cwe_info["cwe"],
            "severity": severity,
            "cvss_rating": cvss_info["rating"],
            "markdown": markdown.strip(),
            "sections": {
                "summary": summary,
                "steps_to_reproduce": steps,
                "impact": impact,
                "poc": poc,
                "remediation": remediation,
            },
        }

    def _build_summary(self, title: str, cwe_info: dict, url: str, vuln: dict) -> str:
        desc = vuln.get("description", "")
        if desc:
            return desc

        return (
            f"A **{cwe_info['name']}** vulnerability was identified at `{url}`. "
            f"This vulnerability allows an attacker to potentially exploit the application "
            f"through the identified attack vector. The issue was confirmed with a working proof of concept."
        )

    def _build_steps_to_reproduce(self, url: str, method: str, parameter: str,
                                    payload: str, request_data: dict) -> str:
        steps = []
        steps.append(f"1. Navigate to: `{url}`")

        if method.upper() == "POST" and parameter:
            steps.append(f"2. In the `{parameter}` parameter, inject the following payload:")
            steps.append(f"   ```\n   {payload}\n   ```")
            steps.append(f"3. Submit the form using {method} method")
        elif parameter:
            steps.append(f"2. Modify the `{parameter}` parameter with the following payload:")
            steps.append(f"   ```\n   {payload}\n   ```")
            steps.append(f"3. Send the request")
        elif payload:
            steps.append(f"2. Use the following payload:")
            steps.append(f"   ```\n   {payload}\n   ```")
            steps.append(f"3. Observe the response")

        if request_data:
            curl_cmd = self._build_curl(url, method, parameter, payload, request_data)
            if curl_cmd:
                steps.append(f"\n**cURL command:**\n```bash\n{curl_cmd}\n```")

        steps.append(f"\n4. Observe that the vulnerability is triggered as shown in the PoC section below.")

        return "\n".join(steps)

    def _build_impact(self, vuln_type: str, cwe_info: dict, severity: str, vuln: dict) -> str:
        impact_map = {
            "sqli": "An attacker can extract, modify, or delete data from the database. In severe cases, this can lead to full database compromise, authentication bypass, or remote code execution via SQL injection techniques.",
            "sqli_blind": "An attacker can extract sensitive data from the database using blind SQL injection techniques (boolean-based or time-based). This can lead to full database enumeration and data exfiltration.",
            "xss_reflected": "An attacker can execute arbitrary JavaScript in a victim's browser session by crafting a malicious URL. This can be used to steal session cookies, perform actions on behalf of the user, or redirect to phishing pages.",
            "xss_stored": "An attacker can permanently inject malicious JavaScript that executes for all users viewing the affected page. This can lead to mass session hijacking, credential theft, or malware distribution.",
            "xss_dom": "An attacker can execute arbitrary JavaScript through DOM manipulation, potentially bypassing server-side security controls.",
            "cmd_injection": "An attacker can execute arbitrary operating system commands on the server, potentially leading to full server compromise, data theft, or lateral movement within the infrastructure.",
            "rce": "An attacker can execute arbitrary code on the server, leading to complete system compromise.",
            "ssrf": "An attacker can make the server perform requests to internal services, potentially accessing internal APIs, cloud metadata endpoints, or other restricted resources.",
            "xxe": "An attacker can read arbitrary files from the server, perform SSRF attacks, or cause denial of service through XML External Entity injection.",
            "idor": "An attacker can access or modify resources belonging to other users by manipulating object references, leading to unauthorized data access or account takeover.",
            "csrf": "An attacker can perform actions on behalf of authenticated users without their consent, potentially changing account settings, making purchases, or modifying data.",
            "auth_bypass": "An attacker can bypass authentication mechanisms and gain unauthorized access to protected resources or administrative functions.",
            "deserialization": "An attacker can execute arbitrary code or manipulate application logic through insecure deserialization of user-controlled data.",
            "subdomain_takeover": "An attacker can take control of a subdomain and serve arbitrary content, potentially stealing cookies, conducting phishing attacks, or bypassing CSP protections.",
        }

        impact_text = impact_map.get(vuln_type,
            f"This {cwe_info['name']} vulnerability ({cwe_info['cwe']}) can be exploited "
            f"to compromise the security of the application and its users.")

        return impact_text

    def _build_poc(self, request_data: dict, response_data: dict, payload: str) -> str:
        parts = []

        if request_data:
            req_str = ""
            if isinstance(request_data, dict):
                method = request_data.get("method", "GET")
                url = request_data.get("url", "")
                headers = request_data.get("headers", {})
                body = request_data.get("body", "")

                req_str = f"{method} {url} HTTP/1.1\n"
                for k, v in headers.items():
                    req_str += f"{k}: {v}\n"
                if body:
                    req_str += f"\n{body}"
            else:
                req_str = str(request_data)

            if req_str.strip():
                parts.append(f"**Request:**\n```http\n{req_str.strip()}\n```")

        if response_data:
            resp_str = ""
            if isinstance(response_data, dict):
                status = response_data.get("status_code", "")
                body = response_data.get("body", "")
                # Truncate long responses
                if body and len(body) > 500:
                    body = body[:500] + "\n... (truncated)"
                resp_str = f"HTTP/1.1 {status}\n\n{body}" if status else (body or "")
            else:
                resp_str = str(response_data)[:500]

            if resp_str.strip():
                parts.append(f"**Response (relevant portion):**\n```http\n{resp_str.strip()}\n```")

        if not parts and payload:
            parts.append(f"**Payload used:**\n```\n{payload}\n```")

        if not parts:
            parts.append("*Proof of concept details are available in the full scan report.*")

        return "\n\n".join(parts)

    def _build_remediation(self, existing: str, vuln_type: str) -> str:
        if existing:
            return existing

        remediation_map = {
            "sqli": "Use parameterized queries (prepared statements) for all database interactions. Implement input validation and escape special characters. Consider using an ORM.",
            "sqli_blind": "Use parameterized queries (prepared statements) for all database interactions. Implement input validation and escape special characters.",
            "xss_reflected": "Encode all user input before reflecting it in HTML responses. Implement Content Security Policy (CSP) headers. Use framework-provided auto-escaping.",
            "xss_stored": "Sanitize and encode all user input before storing and displaying it. Implement CSP headers. Use allowlists for permitted HTML tags if rich text is needed.",
            "cmd_injection": "Avoid passing user input to system commands. If necessary, use allowlists for permitted values and parameterized command execution.",
            "ssrf": "Validate and sanitize all URLs provided by users. Implement allowlists for permitted domains/IPs. Block access to internal network ranges and cloud metadata endpoints.",
            "xxe": "Disable external entity processing in XML parsers. Use JSON instead of XML where possible. If XML is required, use a properly configured parser with DTD processing disabled.",
            "idor": "Implement proper authorization checks for all object access. Use indirect reference maps or UUIDs instead of sequential IDs. Verify user permissions server-side.",
            "csrf": "Implement anti-CSRF tokens for all state-changing operations. Use SameSite cookie attribute. Verify Origin/Referer headers.",
        }

        return remediation_map.get(vuln_type,
            "Review the vulnerability details and implement appropriate security controls. "
            "Consult OWASP guidelines for recommended mitigations.")

    def _build_curl(self, url: str, method: str, parameter: str, payload: str,
                     request_data: dict) -> str:
        """Build a cURL command for the PoC."""
        parts = ["curl"]

        if method.upper() != "GET":
            parts.append(f"-X {method.upper()}")

        # Add headers from request_data
        if isinstance(request_data, dict):
            for k, v in request_data.get("headers", {}).items():
                parts.append(f'-H "{k}: {v}"')

            body = request_data.get("body", "")
            if body:
                # Escape single quotes in body
                body_escaped = body.replace("'", "'\\''")
                parts.append(f"-d '{body_escaped}'")
            elif method.upper() == "POST" and parameter and payload:
                payload_escaped = payload.replace("'", "'\\''")
                parts.append(f"-d '{parameter}={payload_escaped}'")

        parts.append(f'"{url}"')

        return " \\\n  ".join(parts)


def generate_hackerone_report(vuln: dict) -> dict:
    """Convenience function to generate a HackerOne report."""
    return HackerOneReport().generate(vuln)
